# Generated by Django 4.0.1 on 2022-01-17 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelsdemo', '0002_musician_person_shirt_size_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('short_name', models.CharField(max_length=100)),
                ('phone', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='patronymic',
            field=models.CharField(default='anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelsdemo.department'),
        ),
    ]
